version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: transitadmin
      POSTGRES_PASSWORD: gtfsuser0000
      POSTGRES_DB: gtfs_del
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: gtfs_del
      DB_USER: transitadmin
      DB_PASS: gtfsuser0000
      DATABASE_URL: postgresql://transitadmin:gtfsuser0000@db/gtfs_del
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data: